import csv

# addcol2.py - 
# takes a colors3.csv generated by analyze_color.py (and sorted in Excel),  
# and adds grid_x and grid_y columns (wraps arbitrarily at 150 across). 
# Produces a big ol' square!

rows = []
current = 0
counter = 0

with open('colors3.csv', newline='') as csvfile:
  lines = csv.reader(csvfile)
  for i, row in enumerate(lines):
    if (i is 0):
      rows.append(row)
    else:
      if (counter > 150):
        current += 1
        counter = 0
      rows.append(row[:5] + [str(current), str(counter)])
      counter += 1

with open('colors4.csv', 'w', newline='') as f:
  writer = csv.writer(f)
  writer.writerows(rows)

print('all done')