import csv

# addcol.py - 
# takes the colors.csv generated by analyze_color.py, which was 
# already sorted (post-Python) in Excel, and numbers the grid_x and grid_y 
# columns, saves to colors2.csv. Produces a histogram like layout!

rows = []
current = -1
counter = 0

with open('colors.csv', newline='') as csvfile:
  lines = csv.reader(csvfile)
  for i, row in enumerate(lines):
    if (i is 0):
      rows.append(row)
    else:
      if (int(current) < int(row[5])):
        current = int(row[5])
        counter = 0
      rows.append(row[:6] + [str(counter)])
      counter += 1

with open('colors2.csv', 'w', newline='') as f:
  writer = csv.writer(f)
  writer.writerows(rows)

print('all done')